### ISSUE TITLE
Can't play casual

### ISSUE THREAD

**Issue by WarferJerBerger** [furn/TF2hud#12]
I just started to play casual again. and I would like to b able to play it without my friends having to invite me

**Comment by AuroraTF** [comment]
as aegis probably wont fix anything any time soon I will have a look as soon as I can

**Comment by furn** [comment]
You need to click on the "Maintained by Aegis" text box to access the casual menu

**Comment by AuroraTF** [comment]
🤔

**Comment by furn** [comment]
It's been like that since the hud was out years ago. It's a "FEATURE"

**Comment by AuroraTF** [comment]
I swear that was the training button for a while
