### ISSUE TITLE
MM H.U.D. is broken

### ISSUE THREAD

**Issue by SirRahmed** [furn/TF2hud#3]
After the recent stress tests, the TF2 team have implemented new H.U.D. elements into the original TF2 H.U.D.

The issue is that these aren't in the 'Ace' H.U.D. you have here
(i.e. Comp. 10 second countdown not showing, Only 1 team showing in pre-match times)
I have already sent an email to the youtuber Aegis regarding the issue, and he said he will add them in later. As the creator of the H.U.D. I hope you can resolve this issue, so we can all play comp. properly in comp. servers - instead of pub stomping! (It's getting boring now...)

**Comment by furn** [comment]
Should be fixed
