### ISSUE TITLE
Koth TImer

### ISSUE THREAD

**Issue by Winterzduck** [furn/TF2hud#5]
When updating your hud I managed to break the koth timer and from watching your stream I see you have an older commit. If you check my version of the hud I have now fixed the problem. I'm also working on making the winpanel look how it used to.

**Comment by furn** [comment]
I used this version yesterday and the koth timer worked just fine, are you sure it's still broken?

**Comment by Winterzduck** [comment]
In your stream I saw the backgrounds weren't there and I was having the same problem so I'm 99% sure they are broken.
